update

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -32,26 +32,75 @@ set -e
 a() { sed 's/^/-----> /'; }
 i() { sed 's/^/       /'; }
 
+# URLs of the Ubuntu packages to install (see NOTES.md for how to obtain them)
 case "$STACK" in
+  heroku-20)
+    # See https://packages.ubuntu.com/focal/graphviz
+    package_urls=(http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-liberation/fonts-liberation_1.07.4-11_all.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/a/ann/libann0_1.1.2+doc-7build1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/libcdt5_2.42.2-3build2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/libcgraph6_2.42.2-3build2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/gts/libgts-0.7-5_0.7.6+darcs121130-4_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/libpathplan4_2.42.2-3build2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/libgvc6_2.42.2-3build2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/libgvpr2_2.42.2-3build2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/liblab-gamut1_2.42.2-3build2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/x/xorg/x11-common_7.7+19ubuntu14_all.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libi/libice/libice6_1.0.10-0ubuntu1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libs/libsm/libsm6_1.2.3-1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libx/libxt/libxt6_1.1.5-1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libx/libxmu/libxmu6_1.1.3-0ubuntu1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libx/libxaw/libxaw7_1.0.13-1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/graphviz_2.42.2-3build2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/gts/libgts-bin_0.7.6+darcs121130-4_amd64.deb)
+    graphviz_version="2.42.2"
+    ;;
+  heroku-18)
+    # See https://packages.ubuntu.com/bionic/graphviz
+    package_urls=(http://archive.ubuntu.com/ubuntu/pool/main/x/xorg/x11-common_7.7+19ubuntu7.1_all.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libi/libice/libice6_1.0.9-2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libs/libsm/libsm6_1.2.2-1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-liberation/fonts-liberation_1.07.4-7~18.04.1_all.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/a/ann/libann0_1.1.2+doc-6_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/libcdt5_2.40.1-2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/libcgraph6_2.40.1-2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/gts/libgts-0.7-5_0.7.6+darcs121130-4_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/libpathplan4_2.40.1-2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/libgvc6_2.40.1-2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/libgvpr2_2.40.1-2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/liblab-gamut1_2.40.1-2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libx/libxt/libxt6_1.1.5-1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libx/libxmu/libxmu6_1.1.2-2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libx/libxaw/libxaw7_1.0.13-1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/graphviz/graphviz_2.40.1-2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/universe/g/gts/libgts-bin_0.7.6+darcs121130-4_amd64.deb)
+    graphviz_version="2.40.1"
+    ;;
   heroku-16)
-    echo "Installing Graphviz version 2.38.0" | a
-    echo "(Ubuntu package graphviz_2.38.0-12ubuntu2.1_amd64.deb)" | i
-    # URL can be found out with: apt-cache show graphviz | grep Filename
-    url='http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/graphviz_2.38.0-12ubuntu2.1_amd64.deb' ;;
-  cedar-14)
-    echo "Installing Graphviz version 2.36.0" | a
-    echo "(Ubuntu package graphviz_2.36.0-0ubuntu3.1_amd64.deb)" | i
-    # URL can be found out with: apt-cache show graphviz | grep Filename
-    url='http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/graphviz_2.36.0-0ubuntu3.1_amd64.deb' ;;
-  cedar)
-    echo "Installing Graphviz version 2.20.2" | a
-    echo "(Ubuntu package graphviz_2.20.2-8ubuntu3.2_amd64.deb)" | i
-    # URL can be found out with: apt-cache show graphviz | grep Filename
-    url='http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/graphviz_2.20.2-8ubuntu3.2_amd64.deb' ;;
+    # See https://packages.ubuntu.com/xenial/graphviz
+    package_urls=(http://archive.ubuntu.com/ubuntu/pool/main/x/xorg/x11-common_7.7+13ubuntu3.1_all.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libi/libice/libice6_1.0.9-1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libs/libsm/libsm6_1.2.2-1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-liberation/fonts-liberation_1.07.4-1_all.deb
+http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/libcdt5_2.38.0-12ubuntu2.1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/libcgraph6_2.38.0-12ubuntu2.1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/libpathplan4_2.38.0-12ubuntu2.1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/libgvc6_2.38.0-12ubuntu2.1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/libgvpr2_2.38.0-12ubuntu2.1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libx/libxt/libxt6_1.1.5-0ubuntu1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libx/libxmu/libxmu6_1.1.2-2_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/libx/libxaw/libxaw7_1.0.13-1_amd64.deb
+http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/graphviz_2.38.0-12ubuntu2.1_amd64.deb)
+    graphviz_version="2.38.0"
+    ;;
   *)
-    echo "Buildpack error: unsupported stack: $STACK" | a
-    exit 1 ;;
+    echo "Error: unknown Heroku stack: $STACK" | a
+    echo "Report on https://github.com/weibeld/heroku-buildpack-graphviz/issues" | i
+    exit 1
+    ;;
 esac
+echo "Your app uses the $STACK stack" | a
+echo "Will install Graphviz version $graphviz_version" | i
 
 # Download package
 d=$(mktemp -dt XXXX)
